<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnMNMkg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnMNMkg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCnMNMkg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCnMNMkg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCnMNMkg\App_KernelDevDebugContainer([
    'container.build_hash' => 'CnMNMkg',
    'container.build_id' => 'e1d9acb7',
    'container.build_time' => 1672914371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnMNMkg');
